name: Java CI with Docker

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Stop and Remove Old Container
      run: |
        docker stop chemical-ordering-system-dev || true
        docker rm chemical-ordering-system-dev || true
        docker-compose -f /home/ubuntu/chemical-ordering-system/dev/docker-compose.yml down

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests -Dmaven.compiler.fork=true -Djava.util.Arrays.useLegacyMergeSort=true --file /home/ubuntu/actions-runner/_work/uni_chemicals_ordering_system/uni_chemicals_ordering_system/backend/uni_chemicals_ordering_system/chemical-ordering-system/pom.xml

    - name: Move JAR file to DEV directory
      run: mv /home/ubuntu/actions-runner/_work/uni_chemicals_ordering_system/uni_chemicals_ordering_system/backend/uni_chemicals_ordering_system/chemical-ordering-system/target/chemical-ordering-system-0.0.1-SNAPSHOT.jar /home/ubuntu/chemical-ordering-system/dev/

    - name: Build Docker DEV image
      run: |
        docker build --memory=512m -t chemical-ordering-system-dev -f /home/ubuntu/chemical-ordering-system/dev/Dockerfile /home/ubuntu/chemical-ordering-system/dev/

    - name: Run New Container
      run: |
        docker-compose -f /home/ubuntu/chemical-ordering-system/dev/docker-compose.yml up -d

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install Node.js dependencies
      working-directory: /home/ubuntu/actions-runner/_work/uni_chemicals_ordering_system/uni_chemicals_ordering_system/frontend/ChemicalOrderingSystem
      run: npm install

    - name: Build React app
      working-directory: /home/ubuntu/actions-runner/_work/uni_chemicals_ordering_system/uni_chemicals_ordering_system/frontend/ChemicalOrderingSystem
      run: npm run build

    - name: Clean up Docker
      run: |
        docker system prune -f
