name: Java CI with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests --file /home/ubuntu/actions-runner/_work/uni_chemicals_ordering_system/uni_chemicals_ordering_system/backend/uni_chemicals_ordering_system/chemical-ordering-system/pom.xml

    - name: Build Docker image
      run: |
        docker build -t chemical-ordering-system-dev -f /home/ubuntu/Dockerfile .

    - name: Stop and Remove Old Container
      run: |
        docker stop chemical-ordering-system-dev || true
        docker rm chemical-ordering-system-dev || true

    - name: Run New Container
      run: |
        docker run -d --name chemical-ordering-system-dev -p 8080:8080 chemical-ordering-system-dev
